version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    command: uvicorn server.app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env.example
    volumes:
      - ./server:/app/server
      - ./scripts:/app/scripts
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: lingyan
      POSTGRES_USER: lingyan
      POSTGRES_PASSWORD: lingyan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
