name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
      - name: Run pytest
        run: python -m pytest --maxfail=1 --disable-warnings

  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Flutter pub get
        working-directory: app
        run: flutter pub get
      - name: Flutter analyze
        working-directory: app
        run: flutter analyze

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Flutter pub get
        working-directory: app
        run: flutter pub get
      - name: Flutter tests
        working-directory: app
        run: flutter test

  integration:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
      - name: Start FastAPI service
        run: |
          uvicorn server.app.main:app --host 0.0.0.0 --port 8000 &
          echo $! > uvicorn.pid
      - name: Wait for API
        run: |
          for i in {1..20}; do
            if curl -s http://127.0.0.1:8000/health >/dev/null; then
              exit 0
            fi
            sleep 1
          done
          echo "API did not start in time" >&2
          exit 1
      - name: Run smoke script
        run: python scripts/integration_smoke_test.py --base-url http://127.0.0.1:8000
      - name: Stop FastAPI service
        if: always()
        run: |
          if [ -f uvicorn.pid ]; then
            kill $(cat uvicorn.pid) || true
          fi
